# Generated by Django 4.0.1 on 2022-01-08 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video_Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.influencer')),
            ],
        ),
        migrations.CreateModel(
            name='Image_Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.influencer')),
            ],
        ),
    ]
