# Generated by Django 3.2.11 on 2022-01-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_auto_20220106_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='interests',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
