# Generated by Django 3.2.11 on 2022-01-06 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_influencer_interests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencer',
            name='interests',
        ),
    ]
