# Generated by Django 4.0.1 on 2022-01-09 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_alter_contract_influencer_alter_contract_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='signature',
        ),
    ]
