# Generated by Django 4.0.1 on 2022-01-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_remove_contract_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='signature',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
